#:schema node_modules/wrangler/config-schema.json
name = "crm-backend"
main = "server/server.js"
compatibility_date = "2024-04-03"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "crm-db"
database_id = "1bff015e-7780-43d3-98cc-3e7f0947ce6a"
